### ISSUE TITLE
model cannot be compiled because it has no loss to optimize.

### ISSUE THREAD

**Issue by LeiiY** [sayakpaul/Knowledge-Distillation-in-Keras#1]
hello，i want to use ur script `Distillation_with_Transfer_Learning.ipynb`，and my model defined in the following：
![image](https://user-images.githubusercontent.com/28568741/98903481-a989d480-24f2-11eb-98d2-2ce7ab576f4a.png)

get_kd_loss and ClassStudent are same of yours，
![image](https://user-images.githubusercontent.com/28568741/98903441-8fe88d00-24f2-11eb-8c95-14c63d01a78b.png)

how ever，i got `ValueError: The model cannot be compiled because it has no loss to optimize.`
could u tell me why is it？

![image](https://user-images.githubusercontent.com/28568741/98903370-692a5680-24f2-11eb-8238-0cfcd6a35b4a.png)

**Comment by sayakpaul** [comment]
It's hard for me to tell why this is happening without looking at the full class code.
